### ISSUE TITLE
Command `import` doesn't work on Windows

### ISSUE THREAD

**Issue by barinbritva** [humblepenguinn/envio#8]
The lib looks interesting for me. I tried to use it in my project, but got an error while importing my `.env` file to envoi profile. I cleaned up the file and kept only one variable just for an example.

I have a test `.env` file:
```
FEATURE_CUSTOM_AUTH_POPUP=true
```

I run `envoi import .env my-profile`

I get an error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }', src/lib.rs:438:10
stack backtrace:
   0:           0x8af440 - std::backtrace_rs::backtrace::dbghelp::trace::h0dc1cf386a5df1cd
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src\..\..\backtrace\src\backtrace/dbghelp.rs:98:5
   1:           0x8af440 - std::backtrace_rs::backtrace::trace_unsynchronized::h36721138064e13f0
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src\..\..\backtrace\src\backtrace/mod.rs:66:5
   2:           0x8af440 - std::sys_common::backtrace::_print_fmt::ha9b27eb44c93d960
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src\sys_common/backtrace.rs:65:5
   3:           0x8af440 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h79886c501d528d51
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src\sys_common/backtrace.rs:44:22
   4:           0x90f04b - core::fmt::write::h29f886d793a3c470
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\core\src\fmt/mod.rs:1213:17
   5:           0x8a1ff5 - std::io::Write::write_fmt::h4af9d02caf84da95
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src\io/mod.rs:1682:15
   6:           0x8af194 - std::sys_common::backtrace::_print::h7bc8b91c42c6b465
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src\sys_common/backtrace.rs:47:5
   7:           0x8af194 - std::sys_common::backtrace::print::h5c02d637f1374aec
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src\sys_common/backtrace.rs:34:9
   8:           0x8b24df - std::panicking::default_hook::{{closure}}::hb4ad508e3ca0b358
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src/panicking.rs:267:22
   9:           0x8b21b3 - std::panicking::default_hook::hdb151db9713cfc98
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src/panicking.rs:286:9
  10:           0x8b2e29 - std::panicking::rust_panic_with_hook::h4550c1124a1c8a4f
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src/panicking.rs:688:13
  11:           0x8b2b96 - std::panicking::begin_panic_handler::{{closure}}::haadeea136a4af3b4
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src/panicking.rs:579:13
  12:           0x8aff6f - std::sys_common::backtrace::__rust_end_short_backtrace::hc224062df081731d
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src\sys_common/backtrace.rs:137:18
  13:           0x8b28a0 - rust_begin_unwind
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src/panicking.rs:575:5
  14:           0x90b835 - core::panicking::panic_fmt::h1ae32e95b4b1a788
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\core\src/panicking.rs:64:14
  15:           0x90be16 - core::result::unwrap_failed::h8bd87678b87bb845
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\core\src/result.rs:1790:5
  16:           0x438a6c - envio::import_profile::he337f85fe6110813
  17:           0x41bc1e - envio::commands::<impl envio::cli::Command>::run::hd47f498cbd5a07b8
  18:           0x42064f - envio::main::h203bc3a3b9c07d92
  19:           0x427806 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf7689d81c8e323c8
  20:           0x409dec - std::rt::lang_start::{{closure}}::h37a55eb61948c28a
  21:           0x893bf5 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h10e6b3810a97f594
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\core\src\ops/function.rs:287:13
  22:           0x893bf5 - std::panicking::try::do_call::hc0c08aef0d307148
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src/panicking.rs:483:40
  23:           0x893bf5 - std::panicking::try::hf8b174b6af1ac35c
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src/panicking.rs:447:19
  24:           0x893bf5 - std::panic::catch_unwind::h85d6d1a0b4671865
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src/panic.rs:140:14
  25:           0x893bf5 - std::rt::lang_start_internal::{{closure}}::h7ca5722ac975c7be
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src/rt.rs:148:48
  26:           0x893bf5 - std::panicking::try::do_call::h741061858f588bf2
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src/panicking.rs:483:40
  27:           0x893bf5 - std::panicking::try::h6abad9e74e6bdc5f
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src/panicking.rs:447:19
  28:           0x893bf5 - std::panic::catch_unwind::hf171c5a39891248d
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src/panic.rs:140:14
  29:           0x893bf5 - std::rt::lang_start_internal::h1fbc7ed3cff5c2a6
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src/rt.rs:148:20
  30:           0x420b9d - main
  31:           0x4013c7 - __tmainCRTStartup
  32:           0x4014fb - mainCRTStartup
  33:     0x7ffc994855a0 - <unknown>
  34:     0x7ffc9abc485b - <unknown>
 SurfyII C:\project\speed-dating  fix-lobby-timer  npx cross-env RUST_BACKTRACE=full envio import .\.env speed-dating

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }', src/lib.rs:438:10
stack backtrace:
   0:           0x8af440 - std::backtrace_rs::backtrace::dbghelp::trace::h0dc1cf386a5df1cd
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src\..\..\backtrace\src\backtrace/dbghelp.rs:98:5
   1:           0x8af440 - std::backtrace_rs::backtrace::trace_unsynchronized::h36721138064e13f0
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src\..\..\backtrace\src\backtrace/mod.rs:66:5
   2:           0x8af440 - std::sys_common::backtrace::_print_fmt::ha9b27eb44c93d960
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src\sys_common/backtrace.rs:65:5
   3:           0x8af440 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h79886c501d528d51
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src\sys_common/backtrace.rs:44:22
   4:           0x90f04b - core::fmt::write::h29f886d793a3c470
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\core\src\fmt/mod.rs:1213:17
   5:           0x8a1ff5 - std::io::Write::write_fmt::h4af9d02caf84da95
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src\io/mod.rs:1682:15
   6:           0x8af194 - std::sys_common::backtrace::_print::h7bc8b91c42c6b465
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src\sys_common/backtrace.rs:47:5
   7:           0x8af194 - std::sys_common::backtrace::print::h5c02d637f1374aec
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src\sys_common/backtrace.rs:34:9
   8:           0x8b24df - std::panicking::default_hook::{{closure}}::hb4ad508e3ca0b358
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src/panicking.rs:267:22
   9:           0x8b21b3 - std::panicking::default_hook::hdb151db9713cfc98
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src/panicking.rs:286:9
  10:           0x8b2e29 - std::panicking::rust_panic_with_hook::h4550c1124a1c8a4f
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src/panicking.rs:688:13
  11:           0x8b2b96 - std::panicking::begin_panic_handler::{{closure}}::haadeea136a4af3b4
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src/panicking.rs:579:13
  12:           0x8aff6f - std::sys_common::backtrace::__rust_end_short_backtrace::hc224062df081731d
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src\sys_common/backtrace.rs:137:18
  13:           0x8b28a0 - rust_begin_unwind
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src/panicking.rs:575:5
  14:           0x90b835 - core::panicking::panic_fmt::h1ae32e95b4b1a788
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\core\src/panicking.rs:64:14
  15:           0x90be16 - core::result::unwrap_failed::h8bd87678b87bb845
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\core\src/result.rs:1790:5
  16:           0x438a6c - envio::import_profile::he337f85fe6110813
  17:           0x41bc1e - envio::commands::<impl envio::cli::Command>::run::hd47f498cbd5a07b8
  18:           0x42064f - envio::main::h203bc3a3b9c07d92
  19:           0x427806 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf7689d81c8e323c8
  20:           0x409dec - std::rt::lang_start::{{closure}}::h37a55eb61948c28a
  21:           0x893bf5 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h10e6b3810a97f594
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\core\src\ops/function.rs:287:13
  22:           0x893bf5 - std::panicking::try::do_call::hc0c08aef0d307148
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src/panicking.rs:483:40
  23:           0x893bf5 - std::panicking::try::hf8b174b6af1ac35c
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src/panicking.rs:447:19
  24:           0x893bf5 - std::panic::catch_unwind::h85d6d1a0b4671865
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src/panic.rs:140:14
  25:           0x893bf5 - std::rt::lang_start_internal::{{closure}}::h7ca5722ac975c7be
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src/rt.rs:148:48
  26:           0x893bf5 - std::panicking::try::do_call::h741061858f588bf2
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src/panicking.rs:483:40
  27:           0x893bf5 - std::panicking::try::h6abad9e74e6bdc5f
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src/panicking.rs:447:19
  28:           0x893bf5 - std::panic::catch_unwind::hf171c5a39891248d
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src/panic.rs:140:14
  29:           0x893bf5 - std::rt::lang_start_internal::h1fbc7ed3cff5c2a6
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library\std\src/rt.rs:148:20
  30:           0x420b9d - main
  31:           0x4013c7 - __tmainCRTStartup
  32:           0x4014fb - mainCRTStartup
  33:     0x7ffc994855a0 - <unknown>
  34:     0x7ffc9abc485b - <unknown>
```

**Comment by humblepenguinn** [comment]
Envio's `import` command is designed to import already existing profiles, rather than creating a new profile from a file, which you are trying to do now. 

If a coworker wants to share a profile with you, they can either upload it to the internet and you can import it using the command `envio import <url> <profile_name_to_save_as>`, or they can give you a copy of their profile from the profiles directory on a USB stick or similar. You can then use the command `envio import <file_path> <profile_name_to_save_as>` to add the profile to your own profiles directory. However, keep in mind that in order to use your coworker's profile, you must also know the encryption key for that profile.

I added a few lines of code and now in the latest release (v0.3.0) you can create a new profile using a file using the command below:
`envio create .env myprofile` 

This will create a new profile called `myprofile` with all the environment variables from your .env file

**Comment by humblepenguinn** [comment]
By the way I never ran thorough tests on windows, it was just a couple of tests here and there. So could you provide me some feedback?

**Comment by barinbritva** [comment]
@humblepenguinn thanks for the response! I will definitely try the new version.
Sure, I'll provide a feedback
